### ISSUE TITLE
Bug CSS 수정요청

### ISSUE THREAD

**Issue by tehyoyee** [tehyoyee/find-your-pizza#11]
![image](https://github.com/tehyoyee/find-your-pizza/assets/89984263/7ad14b83-a416-4193-bf92-e7cae5b61ce0)
다시하기 눌렀을 때 배경색 흰색.

**Comment by gkdud3579** [comment]
수정완!
엇 이슈번호안했는데 다음부터 꼭 할게요!

커밋 명 : "Chore: 다시보기버튼 클릭시, 배경 흰색으로 바뀌는 에러 수정"
