### ISSUE TITLE
CSS 모바일화면

### ISSUE THREAD

**Issue by tehyoyee** [tehyoyee/find-your-pizza#12]
모바일 접속시 Css 수정요망![Screenshot_20240319_150150_Chrome.jpg](https://github.com/tehyoyee/find-your-pizza/assets/89984263/4cca0d62-48d4-45bf-b4df-d5c9d1876e34)

![Screenshot_20240319_150135_Chrome.jpg](https://github.com/tehyoyee/find-your-pizza/assets/89984263/000d5b97-4e3b-432c-8de0-4cd975139830)

**Comment by gkdud3579** [comment]
resultPage 수정완!

**Comment by KoreanCow** [comment]
이미지 위치 조정 (완 )
