### ISSUE TITLE
Bug: 윈도우 웹에서 질문지 간격 씹히는 현상 

### ISSUE THREAD

**Issue by gkdud3579** [tehyoyee/find-your-pizza#14]
<img width="281" alt="KakaoTalk_Photo_2024-03-20-11-57-37" src="https://github.com/tehyoyee/find-your-pizza/assets/76105226/9c91928d-e877-4126-ad9a-2dd5cbd7cf15">
<img width="284" alt="KakaoTalk_Photo_2024-03-20-11-57-48" src="https://github.com/tehyoyee/find-your-pizza/assets/76105226/df0bcdde-d0df-4e7b-a033-bee260837b11">
<img width="287" alt="KakaoTalk_Photo_2024-03-20-11-57-52" src="https://github.com/tehyoyee/find-your-pizza/assets/76105226/4b0f11c1-91e6-4368-bd6d-6ebe1b13bc2b">

어제 테스트로 친구에게 테스트를 요청했는데, 질문지 화면 간격이 이렇게 씹히는 현상을 발견했습니다

**Comment by KoreanCow** [comment]
question-answer-btn 
Remove : margin-top: -30px;

해결했습니당
