### ISSUE TITLE
Bug 질문지 띄어쓰기 및 짤림

### ISSUE THREAD

**Issue by tehyoyee** [tehyoyee/find-your-pizza#15]
백엔드 디비 수정 요청.~

<img width="529" alt="image" src="https://github.com/tehyoyee/find-your-pizza/assets/89984263/189af0e5-7143-4325-9460-b35465fc1b84">
<img width="471" alt="image" src="https://github.com/tehyoyee/find-your-pizza/assets/89984263/b375dc96-fbff-454a-a1df-f67847610c80">

**Comment by yongbyn** [comment]
수정 완료

**Comment by gkdud3579** [comment]
> 수정 완료

close with comment 해주시면됩니당!
