### ISSUE TITLE
메인 페이지 배경색 불일치

### ISSUE THREAD

**Issue by ETi0n** [tehyoyee/find-your-pizza#24]
밑 두 사진에 두 메인페이지의 background 색깔이 불일치 합니다. 통일 부탁드려요!

**[처음 메인페이지]**
![image](https://github.com/tehyoyee/find-your-pizza/assets/148210094/208e2dac-2c8e-4abb-a1f2-64da198ca4c4)

**[다시하기 버튼으로 이동 후 메인페이지]**
![image](https://github.com/tehyoyee/find-your-pizza/assets/148210094/430f5060-7572-40b3-813b-ee43ed292161)

**Comment by gkdud3579** [comment]
개인적인 의견입니다만,
메인에 피자아저씨 세포분열말고 피자소라게로 변경하는것이 어떨까요?
번거로우시면 피자아저씨 한명 없애도 좋을 것 같아요!

**Comment by KoreanCow** [comment]
#FFE5C8
배경색 통일 완료
