### ISSUE TITLE
Bug: 기존 쿠키에 uuid가 담겨있을 경우, 공유받은 링크에 연결 불가

### ISSUE THREAD

**Issue by gkdud3579** [tehyoyee/find-your-pizza#27]
기존의 쿠키에 uuid가 담겨있을 경우, 
결과 공유하기 버튼을 통해 uuid가 담겨있는 쿼리 링크를 전달받아도 해당 결과가 아닌 기존에 쿠키에 담겨있는 uuid페이지로 연결되는 이슈 발생

**Comment by tehyoyee** [comment]
그러네용.
방법 2가지 제시합니다.
1. 결과받을때 프론트에서 쿠키를 지우거나
2. 쿠키 대신 쿼리파라미터로 백엔드가 uuid를 받으면 좋을거같네요.
노출되어도 되는 정보라 첨부터 끝까지 노출시켜도 될 듯? 합니다.

**Comment by KoreanCow** [comment]
해결했습니당
쿼리있을때 기존 쿠키 제거 후 쿼리에서 파싱한 값을 쿠키에 넣었어요

**Comment by gkdud3579** [comment]
결과값 안보이는 현상이 되서 다시 예전 코드로 복구했습니다.

**Comment by gkdud3579** [comment]
해당 문제에 나오는 에러코드는 아래와 같습니다
`ocode: "ERR_NETWORK"config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}message: "Network Error"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …}stack: "AxiosError: Network Error\n    at c.onerror (https://www.find-your-pizza.site/static/js/main.ca398d7e.js:2:275233)\n    at Pa.request (https://www.find-your-pizza.site/static/js/main.ca398d7e.js:2:280303)\n    at async https://www.find-your-pizza.site/static/js/main.ca398d7e.js:2:308629"[[Prototype]]: Error
(anonymous) @ ResultPage.js:66
result:1 
        
        
       Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES`
       
       
![image](https://github.com/tehyoyee/find-your-pizza/assets/76105226/b5943b34-d1a3-4d13-a846-8bd37817e5d5)

**Comment by gkdud3579** [comment]
시도1) 네트워크 요청 재시도 로직 추가: Axios 요청이 실패했을 때 자동으로 재시도하는 로직을 구현하여 해결 시도

javascript
```
const fetchData = async () => {
  try {
    const response = await axios.get(`${process.env.REACT_APP_API_URL}/result`, {
      withCredentials: true,
    });
    setFormData(response.data);
    setIsLoading(false);
  } catch (e) {
    console.error(e);
    // 재시도 로직, 예를 들어 재시도 횟수를 제한할 수 있음
    setIsLoading(false);
  }
};
```

시도2) 쿠키 도메인 설정: setCookie와 removeCookie 호출 시 도메인을 명시하여, www가 있는 경우와 없는 경우 모두에서 쿠키를 올바르게 처리할 수 있도록 함

javascript
```
setCookie("uuid", urlUuid, {
  path: "/",
  domain: process.env.REACT_APP_COOKIE_DOMAIN, // 예: .find-your-pizza.site
  secure: true,
  maxAge: 36000,
  sameSite: "none",
});
```

결과) 정상적으로 기존 쿠키를 덮어씌우는 결과는 만들어냈지만, 기존에 다른 결과창이 띄어진 창의 쿠키uuid마저 변경하고, 로딩창이 사라지는 이슈 발생

**Comment by gkdud3579** [comment]
```
 const fetchData = async () => {
      try {
        const response = await axios.get(
          `${process.env.REACT_APP_API_URL}/result`,
          {
            withCredentials: true,
          }
        );
        setTimeout(() => {
          setFormData(response.data);
          setIsLoading(false);
        }, 2000);
      } catch (e) {
        console.error(e);
        setIsLoading(false);
      }
    };
```

사라진 로딩창을 복구시키기위해 로딩창 2초 노출 후, 결과창 나오는 형태로 변경하니 다시 url 복사시 결과창이 사라지는 이슈 발생

**Comment by KoreanCow** [comment]
1. useEffect 두 번째 인자 의 유무
`
useEffect(()=>{
  }, [navigate, cookies.uuid, setCookie, removeCookie]);
  `
이 부분에서 navigate, cookies.uuid, removeCookie의 스테이트, 동작이 감지 시 useEffect안에 로직이 실행되기떄문에
setCookie, 쿼리,  cookie의 기존 값이 계속 변경됨에 따라 계속 fetchData() 함수를 실행해서 
백에 요청을 계속보냈음
`
useEffect(()=> {},[]);
`
초기 한번만 실행하도록 변경하여 axios 통신에러 해결

2. cookie 의 domain이 달랐던 점  
resultPage의 쿠키 발급 코드
        domain: process.env.REACT_APP_COOKIE_DOMAIN // www.find-your-pizza.site
questionPage의 쿠키 발급 코드
        domain: `${process.env.REACT_APP_DOMAIN_URL}` // .find-your-pizza.site
        
`${}의 유무에 따라 쿠키의 DOMAIN이 다르게 발급됨
쿠키 발급 도메인 코드를 일치시켜 기존 쿠키제거, 쿠키 재발급으로 uuid를 일치시킴
